Luhn
Glukozavrik/javascript pull request #11
Opened 2024-03-04 06:06 UTC by Glukozavrik

2024-03-04 19:00 UTC, burtovoy requested changes

2024-03-04 19:00 UTC, burtovoy commented on luhn/luhn.js
> +  numbers = numbers.replace(/\s+/g, '').split('');
Давай без регулярок переделаем

2024-03-04 19:00 UTC, burtovoy commented on luhn/luhn.js
> +    if (numbers[i] !== undefined) {
можно просто !numbers[i] – с  undefined не сравнивают

2024-03-05 06:17 UTC, Glukozavrik commented on luhn/luhn.js
> +  numbers = numbers.replace(/\s+/g, '').split('');
Заменил

2024-03-05 06:18 UTC, Glukozavrik commented on luhn/luhn.js
> +    if (numbers[i] !== undefined) {
Заменил на (!(!spl[i]))

2024-03-05 18:30 UTC, merged